baseURL: https://denis-or.com.br/
languageCode: pt_br
DefaultContentLanguage: pt_br
title: "Denis OR"
theme: anatole
summarylength: 10
enableEmoji: yes
enableRobotsTXT: yes
pygmentsUseClasses: yes
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
publishDir: docs/
params:
  author: "Denis Rodrigues"
  customCss: ['css/resume_adap.css','css/style.css']
  customJs: []
  description: "Geógrafo, Doutorando e Mestre em Epidemiologia em Saúde Pública pela Escola Nacional de Saúde Pública - ENSP/FIOCRUZ. Experiência na área de Saúde Pública, com ênfase em Epidemiologia e Vigilância em Saúde."
  doNotLoadAnimations: true
  disableThemeSwitcher: true # Theme switcher is enabled by default
  # favicon: favicons/
  # images: images/site-feature-image.png
  keywords: ''
  mainSections: post
  math:
    enable: true
    use: "katex"
  # profilePicture: images/profile.jpg
  profilePicture: "images/pp.jpg"
  simpleAnalytics: {}
  socialIcons:
    - icon: fab fa-linkedin
      title: Linkedin
      url: https://www.linkedin.com/in/denis-or/
    - icon: fab fa-orcid
      title: Orcid
      url: https://orcid.org/0000-0003-3748-876X
    - icon: fas fa-graduation-cap
      title: lattes
      url: http://lattes.cnpq.br/7838408308841051
    - icon: fab fa-github
      title: GitHub
      url: https://github.com/denis-or
    - icon: fab fa-instagram
      title: instagram
      url: https://www.instagram.com/catoper.mg/
    - icon: fab fa-twitter
      title: twitter
      url: https://twitter.com/Catoper
    - icon: fas fa-envelope
      title: e-mail
      url: mailto:catoper@gmail.com
  title: "Denis OR"
  readMore: true
menu:
  main:
    - identifier: home
      name: Inicio
      url: /
      weight: 100
    - identifier: posts
      name: Blog
      url: /post/
      weight: 200
    - identifier: about
      name: Sobre
      url: /about/
      weight: 300
    - identifier: cv
      name: Currículo
      url: /cv_/
      weight: 300
    - identifier: experience
      name: Experiência Profissional
      url: /experience/
      weight: 300
    # - identifier: contact
    #   name: Contact
    #   url: /contact/
    #   weight: 400
