baseURL: https://denis-or.github.io/
languageCode: pt_br
DefaultContentLanguage: pt_br
# title: Geoepidemiologia
theme: anatole
summarylength: 10
enableEmoji: yes
enableRobotsTXT: yes
pygmentsUseClasses: yes
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
publishDir: docs/
params:
  author: Denis Rodrigues
  customCss: []
  customJs: []
  description: "Geógrafo, Doutorando e Mestre em Epidemiologia em Saúde Pública pela Escola Nacional de Saúde Pública - ENSP/FIOCRUZ. Experiência na área de Saúde Pública, com ênfase em Epidemiologia e Vigilância em Saúde."
  doNotLoadAnimations: no
  # favicon: favicons/
  # images: images/site-feature-image.png
  keywords: ''
  mainSections: Posts
  math:
    enable: no
    use: katex
  # profilePicture: images/profile.jpg
  profilePicture: images/pp.jpg
  simpleAnalytics: {}
  socialIcons:
    - icon: fab fa-linkedin
      title: Linkedin
      url: https://www.linkedin.com/in/denis-or/
    - icon: fab fa-github
      title: GitHub
      url: https://github.com/denis-or
    - icon: fab fa-instagram
      title: instagram
      url: https://www.instagram.com/catoper.mg/
    - icon: fab fa-twitter
      title: twitter
      url: https://twitter.com/Catoper
    - icon: fas fa-envelope
      title: e-mail
      url: mailto:catoper@gmail.com
  title: Denis Rodrigues
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 100
    - identifier: posts
      name: Posts
      url: /post/
      weight: 200
    # - identifier: about
    #   name: About
    #   url: /about/
    #   weight: 300
    # - identifier: contact
    #   name: Contact
    #   url: /contact/
    #   weight: 400
