---
title: "Breve análise do Relatório de Transição na área da Saúde"
author: "Denis OR"
date: '2023-01-05'
slug: relatorio_transicao_saude
categories:
tags: []
Description: "Breve análise do Relatório de Transição na área da Saúde"
DisableComments: yes
---

Recentemente, após uma vitória apertada, Lula retorna ao governo. Pós eleição, campanha encerrada, a equipe de transição "entra em campo" para levantar a situação do governo e se inteirar da organização da equipe que, até então, estava à frente das políticas públicas no país.

Participaram cerca de 1 mil pessoas na equipe de transição, sendo pouco provável que todos estiveram efetivamente presente em todos os levantamentos ou análises. Como produto, a equipe sintetizou os achados em um relatório de 100 páginas, destinado ao governo eleito e pode ser acessado [neste link](https://pt.org.br/wp-content/uploads/2022/12/relatorio-final-da-transicao-de-governo-vf-22-02-22.pdf).

Para os que não sabem, iniciei minha "carreira" profissional trabalhando no setor de Vigilância Epidemiológica de um município do sul de Minas Gerais. Neste setor, me especializei em gestão e planejamento de saúde e considero que sou minimamente letrado em políticas de saúde pública e epidemiologia. É sob este olhar que apresento uma breve análise do relatório.

**O relatório**

O relatório teve cerca de duas páginas para destacar a situação na área da saúde (final da página 16 até o começo da página 18), dividido em oito parágrafos. O primeiro deles reforça sobre a crise sanitária que a pandemia de Covid-19 disseminou pelo mundo. E é muito importante que comece assim, pois foi o maior evento de saúde nas últimas décadas, impactando milhões de pessoas pelo mundo, não sendo diferente no Brasil (ou talvez até pior que muitos países). Entretanto, esse parágrafo não trouxe quaisquer revelações sobre o quadro atual do país que já não era sabido por aqueles minimamente bem-informados.

O segundo parágrafo traz generalidades que não precisava de transição para constatar. Cita queda de indicadores de saúde que qualquer busca em indexadores de produção científica traz mais detalhes. Não foi o relatório que revelou isso.

O terceiro parágrafo foca na afirmação de retrocessos nos programas de saúde oriundos de desestruturações de políticas importantes como Programa Nacional de Imunizações (PNI), Mais Médicos, Farmácia Popular, IST-Aids e Política de Saúde da População Negra. Mas de forma genérica, novamente.

No quarto parágrafo aparecem alguns números. Devido ao teto de gastos criado pela Emenda Constitucional 95, pós impeachment, o SUS vem apresentando déficits, se estivéssemos mantendo o modo de gastos antes da emenda. É citada a situação do orçamento de 2023 que reduziria o gasto com programas essenciais e risco de colapso em serviços essenciais.

O quinto parágrafo já traz os encaminhamentos diante o cenário: recuperar orçamento, resgate da postura do ministério e de políticas de saúde fatalmente prejudicadas e que devem ser priorizadas de forma urgente.

O sexto parágrafo fala novamente de filas, mas agora sobre exames e tratamentos "afetados pela pandemia". Ficou uma dúvida se estas filas foram porque não tinha recurso financeiro, não tinha profissional ou os locais não tinham capacidade instalada para realizar os procedimentos. É citada ainda a necessidade de prioridade à "recuperação das áreas" temáticas.

O sétimo parágrafo pode ser encarado como uma continuidade do sexto. Cita alguns temas que não foram introduzidos antes como, por exemplo, transformação digital e complexo econômico e industrial da saúde, embora sejam de grande relevância para autonomia e organização do SUS.

O oitavo parágrafo encerra citando sobre a participação social. Cita conferências de saúde e colegiados sociais outrora desativados ou extintos e a necessidade de reforço ao complexo industrial na área social.

**O que eu esperava?**

Para um relatório feito "a muitas mãos", esperava que revelasse questões não conhecidas e de elevada importância ao povo brasileiro. Contudo, devemos entender que a equipe de transição não tem autonomia plena. Essa equipe pede documentos ao governo que contenham dados sobre o cenário geral e, de alguma forma, detalhes de algum ponto relevante e de interesse para os eleitos. Mas, a equipe do governo que repassa as informações pode não contribuir de forma satisfatória. Mas, ao ler o relatório, senti falta de alguma informação sobre o papel do Ministério, incluindo profissionais que ali atuam/atuavam, no processo de saúde como um todo. Ou seja, o que faltou do Ministério? Pode ser precoce querer entender isso, pois imagino que pode ser que muitas apurações aconteçam durante a gestão e, possivelmente, o desejo da equipe não era focar no processo ou no Ministério.

Na leitura, senti falta de qual o impacto, de fato, dos problemas citados e que poderiam ser apresentados como taxas de variação dos indicadores ou gráficos. Alguma coisa para nos mostrar o quanto aumentou ou diminuiu. E, novamente, o que o Ministério deixou de fazer? Um relatório da transição tão esperado pode também servir como peça de educação, mostrando como uma avaliação de saúde pode ser feita num "cenário de terra arrasada".

Ou seja, senti falta de mais detalhes. O relatório não conseguiu apresentar o que aconteceu com as políticas, deixando dúvidas. Que houve reduções orçamentárias e financeiras já tínhamos acompanhado pela mídia. Mas o que mais? Em algum momento o orçamento e financiamento aparecem, mas começa pelo teto de gastos que é anterior ao governo Bolsonaro. Embora seja um marco no desfinanciamento da saúde, acredito que ser uma oportunidade interessante para resumo do orçamento executado entre 2018 e 2022. Foi explicitada a redução para 2023, mas e antes? Quais áreas se mantém, desde 2018/2019, como a mais prejudicada? Está subentendido no que foi apresentado, mas precisa de um conhecimento amplo de gestão em saúde para captar este ponto.

Achei curiosa a citação das filas na atenção especializada pois, como citei acima, não foi apresentado um impacto (qual a especialidade mais "sofrida" e qual o problema que diz respeito ao Ministério, o que foi deixado por fazer). Já ouvimos que o governo de Lula pretende inserir um programa de "mais especialidades". Será que é isso? Não foi citado. Me parece que isso não foi um diagnóstico interno fruto de uma avaliação do grupo de transição, mas algo incorporado por conselhos como o CONASS (Conselho Nacional de Secretários de Saúde) ou o CONASEMS (Conselho Nacional de Secretários Municipais de Saúde).

No final encontramos algo sobre complexo industrial. Isso foi um problema importante notado durante a pandemia. Nos percebemos dependentes de diversos insumos que o Brasil teria capacidade de ofertar. Isso, inclusive, é área de pesquisa e publicação do novo secretário de ciência e tecnologia do Ministério. Cita também sobre o controle social, mas as conferências aconteceram e, aquelas que não, foi devido à própria pandemia, não foi?

O relatório não trouxe nada sobre a reintrodução do sarampo que já é um fato, sobre os vazamentos de dados da área de saúde, da forma que as comunidades terapêuticas estão inseridas no SUS, a não implementação da política de saúde das comunidades tradicionais, população negra, população lgbtqia+, a ausência de dados confiáveis da atenção primária, entre vários outros pontos.

É óbvio que o relatório teve um viés mais político do que técnico. Respeito isso com total tranquilidade, ainda mais sabendo da qualidade da equipe que inicia no Ministério da Saúde. Mas, sempre me incomoda essa politização de temas de saúde. É uma área que lida diretamente com as vidas das pessoas. Se uma política de saúde existe (ou não) define quem vive (ou quem morre) no país. Um levantamento além do que já se sabia seria interessante e bem vindo. Não tem problema.

Finalizo por aqui e aconselho a todos a acompanhar o andamento das ações, seja através dos Conselhos de Saúde, das mídias (sociais, televisivas etc.). Acredito que muitos pontos faltantes serão apresentados pela nova equipe que comandará o Ministério.
